### ISSUE TITLE
How do I use it on my mac?

### ISSUE THREAD

**Issue by Fulin-Gao** [collinleiber/ClustPy#53]
ERROR: Could not build wheels for clustpy, which is required to install pyproject.toml-based projects

**Comment by collinleiber** [comment]
Make sure python-dev is installed. Did you install Python using brew? If not, you could try: 'brew reinstall python'
See: https://stackoverflow.com/questions/32578106/how-to-install-python-devel-in-mac-os

**Comment by collinleiber** [comment]
We ran some tests and it worked fine on our systems with a previous installation of python-dev.
