### ISSUE TITLE
Wrong class naming in documentation

### ISSUE THREAD

**Issue by jaanisfehling** [collinleiber/ClustPy#55]
Hi,

in the latest docs, there is a feedforward autoencoder in the deep module: https://clustpy.readthedocs.io/en/latest/clustpy.deep.autoencoders.html#module-clustpy.deep.autoencoders.feedforward_autoencoder

Using the latest version of the package from PyPI, it seems that class does not exist. I looked in the module and assume it is named "FlexibleAutoencoder" now.

**Comment by collinleiber** [comment]
This should be fixed by now. The problem was that the documentation always referred to the development version rather than the release version. We have adjusted this.
